services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bmi-server-frontend
    volumes:
      - .:/app
    env_file: .env
    networks:
      - service-network

networks:
  service-network:
    external: true
    driver: overlay
    name: "service-network"